import {beforeAll,expect,test} from 'bun:test';
import {db,migrate,createCompanion} from '../src/store';
import {saveTemplate,listTemplates,deleteTemplate,allowTemplate,listTemplateRevisions} from '../src/templates';
import {openSpecialistDraft,readSpecialistDraft,requestSpecialistTest} from '../src/specialist-drafts';
import {spawnChild} from '../src/delegation';
import {synchronizeSpecialistConnections} from '../src/specialist-connections';
import {setPersonalActiveLimit,completeMachineAdmission,progressMachineAdmissions} from '../src/admission';
const owner='00000000-0000-4000-8000-000000000001';
beforeAll(()=>migrate());
test('deletion removes a specialist and future team access while preserving existing missions and revisions',async()=>{
 const owner=crypto.randomUUID();
 await db`INSERT INTO "user"(id,name,email,"emailVerified") VALUES(${owner},'Deletion regression',${owner+'@example.test'},true)`;
 await setPersonalActiveLimit(owner,1);
 const profile=await saveTemplate(owner,{name:'Delete regression'});
 const parent=await createCompanion(owner,{name:'Parent',provider:'local'});
 await allowTemplate(owner,parent.id,{templateId:profile.id,maxChildren:2});
 const child=await spawnChild(owner,parent.id,null,crypto.randomUUID(),{templateId:profile.id,prompt:'Existing mission'});
 const queued=await spawnChild(owner,parent.id,null,crypto.randomUUID(),{templateId:profile.id,prompt:'Queued mission'});
 expect(queued.admission?.state).toBe('queued');
 expect(await deleteTemplate('another-owner',profile.id)).toBeNull();
 expect((await listTemplates(owner)).some((item:any)=>item.id===profile.id)).toBe(true);
 expect(await deleteTemplate(owner,profile.id)).toEqual({deleted:true});
 expect(await deleteTemplate(owner,profile.id)).toEqual({deleted:true});
 expect((await listTemplates(owner)).some((item:any)=>item.id===profile.id)).toBe(false);
 expect(await listTemplateRevisions(owner,profile.id)).toHaveLength(1);
 const [existing]=await db`SELECT retired_at FROM companions WHERE id=${child.companionId}`;
 expect(existing.retired_at).toBeNull();
 await synchronizeSpecialistConnections(child.companionId);
 await completeMachineAdmission(owner,child.admission!.id);
 await progressMachineAdmissions();
 const [resumed]=await db`SELECT state FROM machine_admission_requests WHERE companion_id=${queued.companionId}`;
 expect(resumed.state).toBe('admitted');
 await synchronizeSpecialistConnections(queued.companionId);
 await expect(spawnChild(owner,parent.id,null,crypto.randomUUID(),{templateId:profile.id,prompt:'New mission'})).rejects.toThrow();
 await expect(allowTemplate(owner,parent.id,{templateId:profile.id,maxChildren:1})).rejects.toThrow();
 await expect(openSpecialistDraft(owner,profile.id,{commandId:crypto.randomUUID()})).rejects.toThrow();
});
test('deleting a draft cancels its preparation and requests computer archival before returning',async()=>{
 const profile=await saveTemplate(owner,{name:'Draft to remove'});
 const {draft}=await openSpecialistDraft(owner,profile.id,{commandId:crypto.randomUUID()});
 const pending=await requestSpecialistTest(owner,profile.id,{commandId:crypto.randomUUID(),expectedGeneration:draft.generation,prompt:'Test'});
 await deleteTemplate(owner,profile.id);
 expect(await readSpecialistDraft(owner,profile.id)).toBeNull();
 const [computer]=await db`SELECT retired_at,archive_requested_at FROM companions WHERE id=${draft.companionId}`;
 expect(computer.retired_at).toBeTruthy();expect(computer.archive_requested_at).toBeTruthy();
 const [operation]=await db`SELECT status FROM specialist_operations WHERE id=${pending.test.id}`;
 expect(operation.status).toBe('failed');
});
