import {beforeAll,expect,test} from 'bun:test';
import {db,migrate,createCompanion} from '../src/store';
import {saveTemplate,allowTemplate} from '../src/templates';
import {attachPlugin,addCustomPlugin,disconnectPlugin} from '../src/plugins';
import {specialistConnections,overrideSpecialistConnection,synchronizeSpecialistConnections} from '../src/specialist-connections';
const owner='00000000-0000-4000-8000-000000000001';
beforeAll(()=>migrate());
test('a team override does not change the default or another team and a revoked override does not fall back',async()=>{
 const profile=await saveTemplate(owner,{name:'Account specialist'});
 const a=await createCompanion(owner,{name:'A',provider:'local'}),b=await createCompanion(owner,{name:'B',provider:'local'});
 await allowTemplate(owner,a.id,{templateId:profile.id,maxChildren:2});await allowTemplate(owner,b.id,{templateId:profile.id,maxChildren:2});
 const first=await addCustomPlugin(owner,{label:'Default',transport:'http',url:'https://example.test/mcp'});
 const second=await addCustomPlugin(owner,{label:'Override',transport:'http',url:'https://example.test/other'});
 await db`INSERT INTO specialist_connections(template_id,slot,account_id) VALUES(${profile.id},'search',${first.id})`;
 await attachPlugin(owner,a.id,second.id,true);
 await overrideSpecialistConnection(owner,a.id,profile.id,{slot:'search',accountId:second.id});
 expect((await specialistConnections(owner,a.id,profile.id))[0].accountId).toBe(second.id);
 expect((await specialistConnections(owner,b.id,profile.id))[0].accountId).toBe(first.id);
 await disconnectPlugin(owner,second.id);
 expect((await specialistConnections(owner,a.id,profile.id))[0].accountId).toBeNull();
 const child=await createCompanion(owner,{name:'Child',provider:'local'});
 await db`UPDATE companions SET temporary=true,parent_id=${a.id},template_id=${profile.id} WHERE id=${child.id}`;
 await expect(db.begin(tx=>synchronizeSpecialistConnections(child.id,tx))).rejects.toThrow('required MCP');
});
