import {createHash} from 'node:crypto';
import {db} from './store';
const globalAdmissionLock=721440140;
export type MachineAdmissionKind='configuration'|'resume';
export type MachineAdmissionState='queued'|'admitted'|'cancelling'|'cancelled'|'completed'|'refused';
export interface MachineAdmissionInput{requestId:string;companionId:string;kind:MachineAdmissionKind}
export interface MachineAdmissionResult{id:string;companionId:string;kind:MachineAdmissionKind;state:MachineAdmissionState;waitingReason:string|null;requestedAt:Date;admittedAt:Date|null}
export class AdmissionConflict extends Error{}
const fingerprint=(input:MachineAdmissionInput)=>createHash('sha256').update(JSON.stringify({companionId:input.companionId,kind:input.kind})).digest('hex');
const result=(row:any):MachineAdmissionResult=>({id:row.id,companionId:row.companion_id,kind:row.kind,state:row.state,waitingReason:row.waiting_reason??null,requestedAt:new Date(row.requested_at),admittedAt:row.admitted_at?new Date(row.admitted_at):null});
async function occupancy(tx:any){const [row]=await tx`SELECT count(*)::int AS count FROM companions c
 WHERE c.retired_at IS NULL AND (
  EXISTS(SELECT 1 FROM machine_admission_requests a WHERE a.companion_id=c.id AND a.state IN ('admitted','cancelling') AND a.released_at IS NULL)
  OR (c.archived_at IS NULL AND (c.endpoint_secret IS NOT NULL OR c.box_id IS NOT NULL OR c.create_started_at IS NOT NULL)))`;
 return Number(row.count);
}
async function decide(tx:any,row:any){const [companion]=await tx`SELECT box_id,endpoint_secret,create_started_at,archived_at FROM companions WHERE id=${row.companion_id} FOR UPDATE`;if(!companion)return null;const alreadyActive=!companion.archived_at&&!!(companion.box_id||companion.endpoint_secret||companion.create_started_at);const [limits]=await tx`SELECT active_limit,starts_per_minute_limit,starts_per_hour_limit,starts_per_day_limit,cooldown_until>now() AS cooling_down FROM machine_provider_limits WHERE singleton=true`;const [starts]=await tx`SELECT count(*) FILTER(WHERE admitted_at>=now()-interval '1 minute')::int AS minute,count(*) FILTER(WHERE admitted_at>=now()-interval '1 hour')::int AS hour,count(*) FILTER(WHERE admitted_at>=now()-interval '1 day')::int AS day FROM machine_admission_requests WHERE start_counted`;let reason:string|null=null;if(limits.cooling_down)reason='provider_cooldown';else if(!alreadyActive&&await occupancy(tx)>=Number(limits.active_limit))reason='provider_active_limit';else if(!alreadyActive&&Number(starts.minute)>=Number(limits.starts_per_minute_limit))reason='provider_start_minute_limit';else if(!alreadyActive&&Number(starts.hour)>=Number(limits.starts_per_hour_limit))reason='provider_start_hour_limit';else if(!alreadyActive&&Number(starts.day)>=Number(limits.starts_per_day_limit))reason='provider_start_day_limit';if(reason){return (await tx`UPDATE machine_admission_requests SET waiting_reason=${reason} WHERE id=${row.id} AND state='queued' RETURNING *`)[0];}const [admitted]=await tx`UPDATE machine_admission_requests SET state='admitted',waiting_reason=null,admitted_at=now(),start_counted=${!alreadyActive} WHERE id=${row.id} AND state='queued' RETURNING *`;if(admitted)await tx`UPDATE companions SET prepare_requested=true,archive_requested_at=null,error=null WHERE id=${row.companion_id} AND retired_at IS NULL`;return admitted;}
export async function configureProviderMachineLimits(input:{active:number;startsPerMinute:number;startsPerHour:number;startsPerDay:number},sql:any=db){if(Object.values(input).some(v=>!Number.isInteger(v)||v<0))throw new AdmissionConflict('Invalid provider limits.');return sql.begin(async(tx:any)=>{await tx`SELECT pg_advisory_xact_lock(${globalAdmissionLock})`;await tx`UPDATE machine_provider_limits SET active_limit=${input.active},starts_per_minute_limit=${input.startsPerMinute},starts_per_hour_limit=${input.startsPerHour},starts_per_day_limit=${input.startsPerDay},updated_at=now() WHERE singleton=true`;return input;});}
export async function requestMachineAdmissionInTransaction(tx:any,ownerId:string,input:MachineAdmissionInput){await tx`SELECT pg_advisory_xact_lock(${globalAdmissionLock})`;const digest=fingerprint(input);const [prior]=await tx`SELECT * FROM machine_admission_requests WHERE id=${input.requestId} AND owner_id=${ownerId}`;if(prior){if(prior.fingerprint!==digest)throw new AdmissionConflict('Admission request identifier changed.');return result(prior);}const [companion]=await tx`SELECT id FROM companions WHERE id=${input.companionId} AND owner_id=${ownerId} AND retired_at IS NULL FOR UPDATE`;if(!companion)throw new AdmissionConflict('Machine unavailable.');if((await tx`SELECT id FROM machine_admission_requests WHERE companion_id=${input.companionId} AND state IN ('queued','admitted','cancelling')`).length)throw new AdmissionConflict('This machine already has an active admission request.');const [queued]=await tx`INSERT INTO machine_admission_requests(id,owner_id,companion_id,kind,fingerprint,state) VALUES(${input.requestId},${ownerId},${input.companionId},${input.kind},${digest},'queued') RETURNING *`;return result(await decide(tx,queued)??queued);}
export async function requestMachineAdmission(ownerId:string,input:MachineAdmissionInput,sql:any=db){return sql.begin((tx:any)=>requestMachineAdmissionInTransaction(tx,ownerId,input));}
export async function progressMachineAdmissions(sql:any=db,options:{eligible?(request:any,sql?:any):Promise<{eligible:boolean;reason?:string}>}={}){for(const candidate of await sql`SELECT * FROM machine_admission_requests WHERE state='queued' ORDER BY requested_at,id LIMIT 100`){const eligible=options.eligible?await options.eligible(candidate,sql):{eligible:true};if(!eligible.eligible){await sql`UPDATE machine_admission_requests SET waiting_reason=${eligible.reason??'ineligible'} WHERE id=${candidate.id}`;continue;}await sql.begin(async(tx:any)=>{await tx`SELECT pg_advisory_xact_lock(${globalAdmissionLock})`;const [current]=await tx`SELECT * FROM machine_admission_requests WHERE id=${candidate.id} AND state='queued' FOR UPDATE`;if(current)await decide(tx,current);});}}
export async function machineAdmissionAllowsEffect(companionId:string,sql:any=db){const [row]=await sql`SELECT NOT EXISTS(SELECT 1 FROM machine_admission_requests WHERE companion_id=${companionId} AND state IN ('queued','cancelling')) AS allowed`;return !!row.allowed;}
export async function recordMachineActivity(ownerId:string,companionId:string,at=new Date(),sql:any=db){return sql`UPDATE companions SET machine_activity_at=GREATEST(COALESCE(machine_activity_at,${at}),${at}) WHERE id=${companionId} AND owner_id=${ownerId} AND retired_at IS NULL RETURNING id`;}
