/** Compact examples for the same owner-scoped services used by the web app. */
export const controlHelp={
 specialist_next_step:{kind:"connections",message:"Connect GitHub and Linear so I can prepare your repositories and read your issues.",providers:["github","linear"]},
 specialist_configure:{expectedGeneration:'Read with specialist_configure {} first',instructions:'Mission for future copies',initScript:'Optional script run once per intervention'},
 specialist_install:{packages:['jq']},specialist_propose_improvement:{summary:'What changed and why',recipe:'Verified installation steps or selected file changes to reconstruct in the current draft'},specialist_keep_alive:{companionId:'Own specialist intervention ID'},

 history_search:{query:'Words or an exact quoted phrase from earlier work',limit:5},
 identity:{},models:{},configure:{name:'Optional name',instructions:'Optional full instructions',modelId:'ID returned by models',avatar:{shape:'0..7',color:'0..10',face:'0..4'}},
 companion_create:{name:'Name',instructions:'Mission'},companions:{},
 routines:{},routine_save:{id:'Omit to create',name:'Daily review',prompt:'Review the repository',cron:'0 9 * * 1-5',timezone:'Europe/Paris',enabled:true},routine_delete:{id:'Routine ID'},routine_history:{id:'Routine ID'},routine_test:{id:'Routine ID'},
 plugin_catalog:{},plugin_check:{accountId:'Connection ID'},plugins:{},plugin_connect:{serverId:'ID from plugin_catalog',label:'Account label'},plugin_select:{accountId:'Connection ID',enabled:true},plugin_disconnect:{accountId:'Connection ID'},plugin_custom:{label:'My MCP',transport:'http',url:'https://example.com/mcp',headers:{}},
 triggers:{},trigger_save:{id:'Omit to create',name:'Main CI',prompt:'Investigate failure',source:'github',mode:'direct',providerAccountId:'GitHub connection ID',target:{repo:'owner/repo',branch:'main'}},trigger_delete:{id:'Trigger ID'},trigger_registration_retry:{operation:'trigger_save',input:{id:'Trigger ID',register:true}},trigger_history:{id:'Trigger ID'},trigger_test:{id:'Trigger ID',payload:{}},
 template_history:{templateId:"Template ID"},template_rollback:{templateId:"Template ID",targetRevision:1,expectedRevision:2},templates:{},template_save:{id:'Omit to create',expectedRevision:'Required to edit',name:'Coder',instructions:'Coding mission',avatar:{shape:0,color:2,face:0}},template_permission:{templateId:'Template ID',maxChildren:2},software_prepare:{templateId:'Template ID',expectedRevision:1,apt:[{name:'jq',version:'exact apt version'}],npm:[{name:'tsx',version:'4.20.6'}]},software_status:{templateId:'Template ID',buildId:'Optional build ID returned by software_prepare'},spawn:{templateId:'Allowed template ID',prompt:'Self-contained task'},adopt_template:{templateId:'Template ID',childId:'Own child ID',expectedRevision:1},
 delegate:{companionId:'Another permanent Companion ID',prompt:'Self-contained task'},task_status:{runId:'Task ID'},task_answer:{runId:'Task ID',questionId:'Pending question ID',answer:'Answer'},task_cancel:{runId:'Task ID'},
 ask_user:{question:'Question for the user',options:['Option A','Option B']},prepare:{},desktop_takeover:{},desktop_release:{},
 maintenance:{},maintenance_inspect:{companionId:'Granted client Companion ID'},maintenance_history:{companionId:'Granted client Companion ID'},maintenance_configure:{companionId:'Granted client Companion ID',configuration:{instructions:'Updated mission'}},maintenance_prepare:{companionId:'Granted client Companion ID'},maintenance_task:{companionId:'Granted client Companion ID',prompt:'Validate installed tools'},
 deliveries:{},delivery_prepare:{clientEmail:'client@example.com',templateIds:[],maintenanceRequested:false,includeSkills:true},
};
