import {createHash,randomBytes} from 'node:crypto';
import {z} from 'zod';
import {config,encrypt} from './config';
import {createMailAdapter,type MailMessage} from './mail';
import {db} from './store';
import {ProductActivationRequired,requireProductActivation} from './billing';
import {queueDeliverySkillExports} from './delivery-skills';
const json=(body:unknown,status=200)=>Response.json(body,{status,headers:{'Cache-Control':'no-store'}}),idSchema=z.string().uuid();
const createSchema=z.object({clientDeliveryId:idSchema,companionId:idSchema,clientEmail:z.string().trim().email().max(320).transform(v=>v.toLowerCase()),maintenanceRequested:z.boolean().default(false),includeSkills:z.boolean().default(true)});
const mailer=createMailAdapter({provider:config.emailProvider,from:config.emailFrom,resendApiKey:config.resendApiKey,smtpHost:config.smtpHost,smtpPort:config.smtpPort,smtpSecure:config.smtpSecure,smtpUser:config.smtpUser,smtpPassword:config.smtpPassword});
let mailOverride:((mail:MailMessage)=>Promise<void>)|null=null;export function setDeliveryMailerForTests(deliver:((mail:MailMessage)=>Promise<void>)|null){mailOverride=deliver;}
async function sendInvite(mail:MailMessage){if(mailOverride)return mailOverride(mail);await mailer.send(mail);}
export async function migrateDelivery(sql:any=db){await sql.unsafe(await Bun.file(new URL('./delivery.sql',import.meta.url)).text());}
export class DeliveryConflict extends Error{}
function deliveryResult(row:any){return{id:row.id,clientEmail:row.recipient_email,expiresAt:row.expires_at,maintenanceRequested:row.maintenance_requested,skillsStatus:row.skills_status,skillsError:row.skills_error};}
export async function createDelivery(ownerId:string,raw:unknown){
 const input=createSchema.parse(raw),fingerprint=createHash('sha256').update(JSON.stringify(input)).digest('hex');
 const [prior]=await db`SELECT * FROM companion_deliveries WHERE source_owner_id=${ownerId} AND client_delivery_id=${input.clientDeliveryId}`;
 if(prior){if(prior.request_fingerprint!==fingerprint)throw new DeliveryConflict('This delivery identifier was already used with different details.');return deliveryResult(prior);}
 const id=crypto.randomUUID(),expiresAt=new Date(Date.now()+14*86_400_000);
 const inserted=await db.begin(async tx=>{const [source]=await tx`SELECT * FROM companions WHERE id=${input.companionId} AND owner_id=${ownerId} AND retired_at IS NULL FOR SHARE`;if(!source)return null;const profile={name:source.name,instructions:source.instructions,avatar:source.avatar??null,modelId:source.model_id??null};const rows=await tx`INSERT INTO companion_deliveries(id,client_delivery_id,request_fingerprint,source_owner_id,source_companion_id,recipient_email,profile_snapshot,maintenance_requested,expires_at,include_skills,skills_status) VALUES(${id},${input.clientDeliveryId},${fingerprint},${ownerId},${input.companionId},${input.clientEmail},${profile},${input.maintenanceRequested},${expiresAt},${input.includeSkills},${input.includeSkills?'pending':'ready'}) ON CONFLICT(source_owner_id,client_delivery_id) DO NOTHING RETURNING id`;if(rows[0]&&input.includeSkills)await queueDeliverySkillExports(tx,{deliveryId:id,ownerId,companionId:input.companionId});return rows;});
 if(!inserted)return null;if(!inserted[0])return createDelivery(ownerId,raw);if(!input.includeSkills)await sendDeliveryReadyInvite(id);const [result]=await db`SELECT * FROM companion_deliveries WHERE id=${id}`;return deliveryResult(result);
}
export type DeliveryInviteResult='sent'|'skipped'|'unknown'|'not_pending';
export async function sendDeliveryReadyInvite(deliveryId:string):Promise<DeliveryInviteResult>{const [delivery]=await db`UPDATE companion_deliveries SET email_status='sending' WHERE id=${deliveryId} AND status='pending' AND skills_status='ready' AND email_status='pending' RETURNING id,recipient_email,profile_snapshot,expires_at`;if(!delivery)return 'not_pending';if(!mailer.isConfigured&&!mailOverride){await db`UPDATE companion_deliveries SET email_status='skipped' WHERE id=${delivery.id}`;return 'skipped';}const link=`${config.authUrl.replace(/\/$/,'')}/deliveries/${delivery.id}`;try{await sendInvite({to:delivery.recipient_email,subject:`${String(delivery.profile_snapshot.name)} is ready for you`,text:`Sign in with ${delivery.recipient_email} to review and activate your independent Companion copy:\n\n${link}`});}catch{await db`UPDATE companion_deliveries SET email_status='unknown' WHERE id=${delivery.id}`;return 'unknown';}await db`UPDATE companion_deliveries SET email_status='sent' WHERE id=${delivery.id}`;return 'sent';}
export async function progressDeliveryInvites(limit=20){const pending=await db`SELECT id FROM companion_deliveries WHERE status='pending' AND expires_at>now() AND skills_status='ready' AND email_status='pending' ORDER BY created_at,id LIMIT ${Math.min(100,Math.max(1,limit))}`;for(const row of pending)await sendDeliveryReadyInvite(row.id);return pending.length;}
export async function acceptDelivery(ownerId:string,deliveryId:string,grantMaintenance:boolean){await requireProductActivation(ownerId);return db.begin(async sql=>{const [user]=await sql`SELECT lower(email) AS email,"emailVerified" AS verified FROM "user" WHERE id=${ownerId}`;if(!user?.verified)throw new DeliveryConflict('Verify your email before accepting this delivery.');const [delivery]=await sql`SELECT * FROM companion_deliveries WHERE id=${deliveryId} FOR UPDATE`;if(!delivery||delivery.recipient_email!==user.email)return null;if(delivery.status==='accepted')return{companionId:delivery.delivered_companion_id,accepted:false};if(delivery.status!=='pending'||new Date(delivery.expires_at)<=new Date())throw new DeliveryConflict('This invitation is no longer available.');if(delivery.skills_status!=='ready')throw new DeliveryConflict(delivery.skills_error??'Portable skills are still being prepared.');const profile=z.object({name:z.string().min(1).max(80),instructions:z.string().max(20_000),avatar:z.unknown().nullable(),modelId:z.string().max(200).nullable().optional()}).parse(delivery.profile_snapshot);const companionId=crypto.randomUUID();const [bundle]=await sql`SELECT bundle_id FROM portable_skill_exports WHERE delivery_id=${deliveryId} AND target_kind='delivery_main' AND status='ready'`;await sql`INSERT INTO companions(id,owner_id,name,instructions,provider,create_key,agent_secret,prepare_requested,skill_bundle_id,model_id) VALUES(${companionId},${ownerId},${profile.name},${profile.instructions},${config.defaultProvider},${crypto.randomUUID()},${encrypt(randomBytes(32).toString('hex'))},true,${bundle?.bundle_id??null},${profile.modelId??null})`;if(profile.avatar!==null)await sql`UPDATE companions SET avatar=${profile.avatar} WHERE id=${companionId}`;if(grantMaintenance&&delivery.maintenance_requested)await sql`INSERT INTO companion_maintenance_grants(delivery_id,companion_id,client_owner_id,maintainer_id) VALUES(${deliveryId},${companionId},${ownerId},${delivery.source_owner_id})`;await sql`UPDATE companion_deliveries SET status='accepted',accepted_by=${ownerId},delivered_companion_id=${companionId},accepted_at=now() WHERE id=${deliveryId}`;return{companionId,accepted:true};});}
export async function canMaintainCompanion(maintainerId:string,companionId:string){return !!(await db`SELECT 1 FROM companion_maintenance_grants WHERE maintainer_id=${maintainerId} AND companion_id=${companionId} AND revoked_at IS NULL`).length;}
export async function handleDelivery(request:Request,ownerId:string){const url=new URL(request.url);if(url.pathname==='/api/deliveries'&&request.method==='GET'){const [user]=await db`SELECT lower(email) AS email FROM "user" WHERE id=${ownerId}`;const [sent,received]=await Promise.all([db`SELECT id,recipient_email AS "clientEmail",status,skills_status AS "skillsStatus",skills_error AS "skillsError",maintenance_requested AS "maintenanceRequested",expires_at AS "expiresAt",accepted_at AS "acceptedAt",delivered_companion_id AS "companionId" FROM companion_deliveries WHERE source_owner_id=${ownerId} ORDER BY created_at DESC`,db`SELECT id,profile_snapshot->>'name' AS name,status,skills_status AS "skillsStatus",skills_error AS "skillsError",maintenance_requested AS "maintenanceRequested",expires_at AS "expiresAt",accepted_at AS "acceptedAt",delivered_companion_id AS "companionId" FROM companion_deliveries WHERE recipient_email=${user.email} ORDER BY created_at DESC`]);return json({sent,received});}if(url.pathname==='/api/deliveries'&&request.method==='POST'){try{const delivery=await createDelivery(ownerId,await request.json());return delivery?json({delivery},201):json({error:'Companion not found.'},404);}catch(error){if(error instanceof DeliveryConflict)return json({error:error.message},409);throw error;}}const match=url.pathname.match(/^\/api\/deliveries\/([^/]+)(?:\/(accept|maintenance))?$/);if(!match)return null;const id=idSchema.parse(match[1]);if(match[2]==='accept'&&request.method==='POST'){try{const body=z.object({grantMaintenance:z.boolean().default(false)}).parse(await request.json().catch(()=>({})));const result=await acceptDelivery(ownerId,id,body.grantMaintenance);return result?json(result):json({error:'Delivery not found.'},404);}catch(error){if(error instanceof DeliveryConflict||error instanceof ProductActivationRequired)return json({error:error.message},409);throw error;}}if(match[2]==='maintenance'&&request.method==='DELETE'){
 return db.begin(async tx=>{
  const rows=await tx`UPDATE companion_maintenance_grants SET revoked_at=now() WHERE delivery_id=${id} AND client_owner_id=${ownerId} AND revoked_at IS NULL RETURNING delivery_id`;
  if(!rows.length)return json({error:'Maintenance access not found.'},404);
  await tx`UPDATE runs r SET cancel_requested=true,status=CASE WHEN r.status='queued' THEN 'cancelled' ELSE r.status END,finished_at=CASE WHEN r.status='queued' THEN now() ELSE r.finished_at END WHERE r.id IN (SELECT run_id FROM maintenance_actions WHERE grant_id=${id}) AND r.status IN ('queued','preparing','running','needs_input')`;
  return json({revoked:true});
 });
}if(!match[2]&&request.method==='DELETE'){const rows=await db`UPDATE companion_deliveries SET status='revoked' WHERE id=${id} AND source_owner_id=${ownerId} AND status='pending' RETURNING id`;return rows.length?json({revoked:true}):json({error:'Pending delivery not found.'},404);}return null;}
