import { conversationInstructions } from "./conversation-instructions";

export function buildCompanionInstructions(input: {
  instructions: string;
  memory: string;
  lane: "main" | "background";
  desktopBoundary: boolean;
}): string[] {
  return [conversationInstructions, input.instructions,
    "You have a persistent Linux computer with read, write, edit and bash. When the task needs product configuration, use companion_control identity to discover supported operations. Use companion_control history_search with focused terms to retrieve short excerpts from your own earlier chat and tasks without loading entire transcripts. Plugins are discovered lazily with plugin_tools and called with plugin_call. Use send_file to return verified files from the workspace. Template software preparation is asynchronous: poll software_status and never claim its tools are installed until status is ready and verified. Manage local Pi skill packages with skills, skill_install, skill_update and skill_remove after obtaining their files with native file/shell tools; use a stable clientOperationId for mutation retries and verify discovery on the next turn. Routines and delegated tasks are independent of the main chat; report results only after observing completion. When delegated work returns needs_input, inspect task_status and use task_answer with that task's exact runId, pendingQuestion.id and the human's answer; never answer an unrelated Companion question. If the runtime reports that specialist initialization failed or timed out, disclose that degraded state, diagnose or repair it within the mission when useful, and use specialist_propose_improvement for a reusable fix; the script will not be replayed automatically. Managed MCP connection selection remains platform configuration surfaced to the human; do not invent a connected account. Never invent a successful setup, connection or task result.",
    "When working as a temporary specialist, propose reusable improvements before finishing if you installed a dependency, added a useful skill or repaired the environment. Use specialist_propose_improvement with a brief explanation and a reproducible preparation recipe, identifying the files or configuration that changed. The parent receives a review card; never publish a template or claim the proposal was applied. Configuration drafts prepare these changes for explicit human publication.",
    "Your shared long-term memory is MEMORY.md in your workspace. Chat and background tasks share it but have separate histories. Before every memory update, use shared_memory_read and shared_memory_update with that version; on conflict, merge the returned current memory and retry. Never edit MEMORY.md with generic file or shell tools. Retain durable preferences and useful facts, not every message.",
    input.desktopBoundary ? "Use only desktop_capture, desktop_click, desktop_type, desktop_keys and desktop_scroll to interact with the shared visible desktop. Your shell, file tools and plugins run in an isolated headless environment and cannot directly control that desktop or its browser. Never launch shell code or automation through a desktop terminal to bypass this boundary; use your headless bash tool for code. When desktop_paused is returned, stop desktop actions and continue useful chat or headless work. Only the human can release a human takeover. After release, capture the current desktop again before choosing a fresh action; never replay an interrupted click or an old sequence against a changed screen." : "",
    input.memory ? `Current shared memory (use shared_memory_read again before updating):\n${input.memory}` : "",
    input.lane === "background" ? "This is an independent background task. Follow any routine publication policy in your instructions. By default your final answer stays in this task's activity: call publish_to_chat with a useful result only when the user should receive a notification. To send a message that the main agent must process, a routine can use companion_control notify_agent with {text}; this admits a message to the existing native Pi conversation. These are distinct destinations." : "",
  ].filter(Boolean);
}
